"""Hook integration for agent learning and session handoff.

Provides:
- record_task_outcome(): Record task completion for SONA learning
- save_handoff(): Auto-save session handoff to HANDOFF.md
"""

import logging
from datetime import UTC, datetime
from pathlib import Path

logger = logging.getLogger(__name__)


def get_project_root() -> Path:
    """Get project root (parent of ai/)."""
    return Path(__file__).parent.parent


def record_task_outcome(
    task_id: str,
    quality: float,
    success: bool,
    duration_seconds: float,
    agent_type: str | None = None,
) -> dict | None:
    """Record task outcome for SONA learning via MCP hooks.

    Uses ruflo_hooks_intelligence_trajectory tools if available.
    """
    try:
        from importlib.util import find_spec

        if find_spec("ruflo_hooks_intelligence_trajectory_start"):
            pass  # SONA available but not actively used yet
    except Exception:  # noqa: S110
        pass

    logger.info(
        "Task completed: %s, success=%s, quality=%s, duration=%.1fs",
        task_id,
        success,
        quality,
        duration_seconds,
    )
    return None


def save_handoff(
    summary: str,
    files_modified: list[str],
    next_steps: list[str],
    task_id: str | None = None,
) -> None:
    """Save session handoff to HANDOFF.md automatically."""
    project_root = get_project_root()
    handoff_path = project_root / "HANDOFF.md"

    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    content = f"""# Cross-Tool Session Handoff
<!-- Auto-generated by ai/hooks.py -->
Updated: {timestamp}

## Last Session Summary
{summary}

## Files Modified
{chr(10).join(f"- {f}" for f in files_modified) if files_modified else "- (none)"}

## Suggested Next Steps
{chr(10).join(f"- {s}" for s in next_steps) if next_steps else "- Continue current task"}

---
_auto-generated, do not edit manually_
"""

    handoff_path.write_text(content, encoding="utf-8")
    print(f"[HOOKS] Handoff saved to {handoff_path}")


def auto_save_handoff() -> None:
    """Auto-save handoff based on recent git changes."""
    project_root = get_project_root()

    try:
        import subprocess

        result = subprocess.run(
            ["git", "status", "--short"],
            cwd=project_root,
            capture_output=True,
            text=True,
            timeout=10,
        )
        modified = [line[3:].strip() for line in result.stdout.splitlines() if line.strip()]
    except Exception:
        modified = []

    summary = f"Auto-saved handoff: {len(modified)} files modified"
    files_modified = modified[:10]
    next_steps = ["Read HANDOFF.md at session start"]

    save_handoff(summary, files_modified, next_steps)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Hook integration for agents")
    parser.add_argument("--save-handoff", action="store_true", help="Auto-save handoff")
    parser.add_argument("--summary", default="", help="Session summary")
    args = parser.parse_args()

    if args.save_handoff:
        auto_save_handoff()
