Section "Device"
    Identifier "NVIDIA Card"
    Driver "nvidia"
    Option "Coolbits" "28"
    Option "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3"
EndSection
