name: Semgrep

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'HANDOFF.md'
      - 'CHANGELOG.md'
      - 'desktop/**'
      - 'systemd/**'
  schedule:
    - cron: '50 12 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
